[tool.poetry]
name = "securedrop-docs"
version = "2.7.0"
description = "SecureDrop documentation for journalists, sources and administrators"
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^7.4.7"
sphinx-autobuild = "^2024.2.4"
sphinx-rtd-theme = "^2.0.0"
