[tool.poetry]
name = "securedrop-docs"
version = "2.6.1"
description = "SecureDrop documentation for journalists, sources and administrators"
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sphinx = "^6.2.1"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.3.0"
